### ISSUE TITLE
Handle, Show error message for no receipts on registered tax type

### ISSUE THREAD

**Issue by rahensonzam** [siphomateke/zra-helper#93]
When a tax type is registered but there are no receipts then it should read the "No Data Found" from the page and display an error "No acknowledgements of returns found"
or "No payment receipts found"

Currently it reads the tax payer profile then says "Tax type not found" error

![no returns](https://user-images.githubusercontent.com/32675705/53886374-8e31ab00-4028-11e9-8f7a-440fe82689ad.png)

**Comment by siphomateke** [comment]
The extension actually already detects the no data found message. It specifically throws the "Tax type not found" when it detects this message. This was implemented before we were getting all registered tax types so it assumed if no data was found, then the tax type did not exist. Since we now know exactly which tax types are registered, we could change this to be a  "No acknowledgements of returns found".

However, an error shouldn't realy be thrown at all when there is just no data. Errors should be reserved for program execution errors. The kind of things that mean the task will have to be re-run.

Because of this, we will just remove the error entirely.
